name: K6 Load Test

on:
  workflow_dispatch:

jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run k6 locally
        uses: grafana/k6-action@v0.2.0
      - name: Run k6 tests and generate HTML reports
        run: |
          k6 run --out html=./report.html getdogid.js
      - name: Archive HTML report
        uses: actions/upload-artifact@v2
        with:
          name: k6-html-report
          path: ./report.html
