name: K6 Load Test

on:
  workflow_dispatch:

jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run local k6 test
      uses: grafana/k6-action@v0.2.0
      with:
        filename: getdogid.js
        flags: --out json=summary.json
    - name: Upload performance test results
      uses: actions/upload-artifact@v1
      with:
       name: k6-summary-report-json
       path: summary.json
    - name: Archive HTML report
      uses: actions/upload-artifact@v1
      with:
       name: k6-summary-report-html
       path: summary.html
       depends-on: k6
