name: K6 Load Test

on:
  workflow_dispatch:

jobs:
  k6:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Install k6
      run: Invoke-WebRequest https://dl.bintray.com/loadimpact/windows/k6-v0.35.1-amd64.msi -OutFile k6.msi
    - name: Install k6
      run: msiexec /i k6.msi /quiet
    - name: Run local k6 test
      uses: grafana/k6-action@v0.2.0
      with:
        filename: getdogid.js
        flags: --out json=summary.json

    - name: Generate HTML report
      run: k6 convert -o summary.html summary.json
      
    - name: Upload performance test results
      uses: actions/upload-artifact@v1
      with:
        name: k6-summary-report-html
        path: summary.html
